In [1]:
from glob import glob
from tqdm import tqdm
import pandas as pd
import shutil

file_marksheet = 'picai_labels/clinical_information/marksheet.csv'
root_dir = '/media/mpmri/mpmri/nnUNet_raw_data/Task2201_picai_baseline/'

In [2]:
marksheet = pd.read_csv(file_marksheet)
logic = marksheet['lesion_ISUP'].str.contains('3') | \
        marksheet['lesion_ISUP'].str.contains('4') | \
        marksheet['lesion_ISUP'].str.contains('5')
marksheet = marksheet[logic]

In [3]:
marksheet

,patient_id,study_id,mri_date,patient_age,psa,psad,prostate_volume,histopath_type,lesion_GS,lesion_ISUP,case_ISUP,case_csPCa
5,10005,1000005,2012-07-18,64,12.10,0.24,51.0,MRBx,"4+3,0+0","3,0",3,YES
8,10008,1000008,2020-12-06,81,11.10,0.20,56.0,SysBx+MRBx,"4+3,3+4","3,2",3,YES
21,10021,1000021,2012-06-18,61,23.00,0.39,60.0,MRBx,4+3,3,3,YES
29,10029,1000029,2017-10-15,64,8.90,0.20,46.0,SysBx+MRBx,"3+4,4+5,3+3","2,5,1",5,YES
32,10032,1000032,2012-08-13,73,19.18,0.34,57.0,MRBx,"4+3,0+0","3,0",3,YES
...,...,...,...,...,...,...,...,...,...,...,...,...
1471,11447,1001471,2018-05-24,74,12.00,NaN,51.0,MRBx,5+3,4,4,YES
1475,11451,1001475,2018-07-02,71,5.58,0.14,44.0,MRBx,4+4,4,4,YES
1486,11462,1001486,2012-05-06,64,9.07,0.16,58.0,MRBx,"4+5,N/A",5,5,YES
1492,11468,1001492,2020-11-07,64,4.30,0.20,23.0,SysBx+MRBx,4+3,3,3,YES
1499,11475,1001499,2012-12-23,56,15.00,0.46,33.0,MRBx,4+5,5,5,YES

In [4]:
for mi, m in tqdm(marksheet.iterrows(), total=len(marksheet)):
    file_image = f"{root_dir}/imagesTr/{m['patient_id']}_{m['study_id']}*"
    file_image = glob(file_image)
    file_label = f"{root_dir}/labelsTr/{m['patient_id']}_{m['study_id']}*"
    file_label = glob(file_label)
    for k in file_image:
        shutil.copyfile(k, f"cases/images/{k.split('/')[-1]}")
    for k in file_label:
        shutil.copyfile(k, f"cases/labels/{k.split('/')[-1]}")

100%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 191/191 [00:22<00:00,  8.34it/s]